version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/myApp
  - source: /scripts/appserver
    destination: /etc/init.d/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/post_install
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: root
