version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/myApp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: root
