#!/bin/sh
### BEGIN INIT INFO
# Provides:          {NAME}
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       {DESCRIPTION}
### END INIT INFO

SCRIPT=/tmp/myApp/scripts/START
RUNAS=ec2-user

PIDFILE=/var/run/appserver.pid
LOGFILE=/var/log/appserver.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'smelly_badges: Service already running' >&2
    return 1
  fi
  echo 'smelly_badges: Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'smelly_badges: Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'smelly_badges: Service not running' >&2
    return 1
  fi
  echo 'smelly_badges: Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'smelly_badges: Service stopped' >&2
}

uninstall() {
  stop
  rm -f "$PIDFILE"
  echo "smelly_badges: log file is not be removed: '$LOGFILE'" >&2
  update-rc.d -f smelly_badges remove
  rm -fv "$0"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
