#!/bin/bash


curl --silent --location https://rpm.nodesource.com/setup_4.x | bash -
yum -y install nodejs nginx

# hack
rm /etc/nginx/nginx.conf
rm /etc/nginx/sites-enabled/site.conf || echo "No site.conf to remove"
